mheyer32/alienbreed3d2

- ab3d2_source/airoutine.s
- ab3d2_source/chunky.s
- ab3d2_source/controlloop.s
- ab3d2_source/hires.s
Mnemonics and pseudo-mnemonics to lowercase for the sake of sanity.
> Source Tidying (bit by bit)

- ab3d2_source/Makefile
- ab3d2_source/airoutine.s
- ab3d2_source/controlloop.s
- ab3d2_source/hires.s
- ab3d2_source/hiresgourwall.s
- ab3d2_source/hireswall.s
- ab3d2_source/macros.i
- ab3d2_source/newanims.s
- ab3d2_source/newloadfromdisk.s
- ab3d2_source/objdrawhires.s
- ab3d2_source/plr1control.s
- ab3d2_source/plr2control.s
- Removes conditional CHEESEY code
- Cheese removed file by file, as separate commits. Just in case.
- Cheese define remains in case some include or other has a dependency (to be verified) 
- Fixes a pair of build time warnings (caused by branch to next instruction due to commented out code)
- Some OCD changes:
- Excessive empty line removal, blank line before label, etc - all experimental to see how it affects readability
> Lactose Intolerance

- ab3d2_source/controlloop.s
- ab3d2_source/defs.i
- ab3d2_source/fall.s
- ab3d2_source/hires.s
- ab3d2_source/leveldata2.s
- ab3d2_source/modules/ai.s
- ab3d2_source/modules/res.s
- ab3d2_source/newaliencontrol.s
- ab3d2_source/newanims.s
- ab3d2_source/newplayershoot.s
- ab3d2_source/objdrawhires.s
- ab3d2_source/objectmove.s
- ab3d2_source/orderzones.s
- ab3d2_source/plr1control.s
- ab3d2_source/plr2control.s
Begins the process of converting EQU offset lists into structures
- Objects defined in Game Link File
- Other structures defined at runtime
> Converting EQU lists to structure definitions

- ab3d2_source/controlloop.s
- ab3d2_source/hires.s
- ab3d2_source/newanims.s
- ab3d2_source/plr1control.s
- ab3d2_source/screensetup.s
manual merge after making a mess of my main, works for me. feel free to reject the changes I have made as I feel they will become out of date quickly with the progress yourself and karlos are making, but, while simple, may offer ideas worth implementing.
> manual merge of my changes to current

- ab3d2_source/hires.s
- ab3d2_source/newanims.s
- ab3d2_source/newplayershoot.s
- ab3d2_source/objdrawhires.s
Mostly division approximations.
- Have left a questionable multiplication enabled in newanims due to strange bug with distant wall texture vertical offsets.
> Optimisations split out of previous PR.

- ab3d2_source/controlloop.s
- ab3d2_source/hires.s
- ab3d2_source/hiresgourwall.s
- ab3d2_source/hireswall.s
- ab3d2_source/leveldata2.s
- ab3d2_source/modules/ai.s
- ab3d2_source/modules/file_io.s
- ab3d2_source/newaliencontrol.s
- ab3d2_source/newanims.s
- ab3d2_source/objdrawhires.s
- ab3d2_source/objectmove.s
- ab3d2_source/pauseopts.s
- ab3d2_source/plr1control.s
- ab3d2_source/plr2control.s
Eliminates dead code. Criteria for elimination:
- Is already commented out
- Unchanged since initial commit (excluding as a consequence of rename operations)
- Not part of unfinished cleanup or potentially intriguing feature (e.g. curved walls)
OR
- Dead code identified / commented out during recent refactoring operations.
> Dead code elimination, low hanging fruit

- ab3d2_source/hires.s
- ab3d2_source/hiresgourwall.s
- ab3d2_source/hireswall.s
- ab3d2_source/newanims.s
- ab3d2_source/objdrawhires.s
Focuses on wall drawing code cleanup (work in progress)
- Identifier and label renaming
- Removal of duplicate lookup tables
> Identifier updates 2

- ab3d2_source/hires.s
- ab3d2_source/screensetup.s
there is a frame timer and 2 sets of timers that can be put around anything you wish to measure. currently one is around c2p+copy, the other, the game loop minus c2p+copy.
needs tidy up, but working. comments welcome.
> added timers for development instrumentation

- ab3d2_source/bss/ai_bss.s
- ab3d2_source/bss/level_bss.s
- ab3d2_source/bss/player_bss.s
- ab3d2_source/defs.i
- ab3d2_source/hires.s
- ab3d2_source/modules/ai.s
- ab3d2_source/modules/dev_inst.s
- ab3d2_source/modules/player.s
- ab3d2_source/newaliencontrol.s
- ab3d2_source/newanims.s
- ab3d2_source/newplayershoot.s
Initial structure refactoring. Moved the additional player pro…perties into the Plr1_Data and Plr2_Data and updated the structure definition to include:
- PlrT_DefaultEnemyFlags_l
- PlrT_GunFrame_w
- PlrT_NoiseVol_w (moved from AI_PlayerNoiseVol)
- PlrT_ObjectDistances_vw
- PlrT_PlrT_ObjectsInLine_vb
> Player Weapon Code - Redux Part 1 - Data

- ab3d2_source/hires.s
- ab3d2_source/hireswall.s
- ab3d2_source/modules/dev_inst.s
- ab3d2_source/modules/dev_macros.i
- ab3d2_source/modules/player.s
Added a "fullbright" developer mode toggle to help with reteturing work. This currently only works on walls due to buggy non-gouraud floor support.
> Dev Mode - Fullbright toggle

- ab3d2_source/newanims.s
Issue #18 - Fix for wrong wall texture offset on doors/lifts
> sugested fix for issue-#18 Door Adjoining Wall Texture

- ab3d2_source/c/system.c
- ab3d2_source/c/system.h
- ab3d2_source/hires.s
- ab3d2_source/modules/player.s
- ab3d2_source/modules/system.s
Reverted to using the assembler mouse functions in the C build to address the vertical wrapping bug for now.
> Work around for vertical mouse wrapping bug.

- ab3d2_source/c/system.c
- ab3d2_source/hires.s
- ab3d2_source/modules/player.s
Hopefully accurate replacement of the vertical mouse movement. Code is a bit weird and could perhaps be improved, but it's not performance critical.
(Note: I don't think the "ELSE IFND" construct worked in vasm).
> Fix C version of Sys_ReadMouse

- ab3d2_source/Makefile
- ab3d2_source/bss/system_bss.s
- ab3d2_source/c/system.c
- ab3d2_source/hires.s
- ab3d2_source/modules/dev_inst.s
- ab3d2_source/modules/draw/draw_floor.s
- ab3d2_source/modules/draw/draw_floor_060.s
- ab3d2_source/modules/player.s
- ab3d2_source/modules/system.s
Adds startup 68060 detection and allows devmode selection of 060 code path.
> Runtime 060 selection

- ab3d2_source/bss/draw_bss.s
- ab3d2_source/bss/tables_bss.s
- ab3d2_source/modules/res.s
Seen in karlos-tkg. Also try to fix wall texture slot 16 not being usable.
> Fix crash on exit when all SFX are used

- .gitignore
- ab3d2_source/bss/system_bss.s
- ab3d2_source/c/main.c
- ab3d2_source/c/menu.c
- ab3d2_source/c/screen.c
- ab3d2_source/c/screen.h
- ab3d2_source/c/system.c
- ab3d2_source/c/system.h
- ab3d2_source/controlloop.s
- ab3d2_source/hires.s
- ab3d2_source/macros.i
- ab3d2_source/menu/menunb.s
- ab3d2_source/modules/file_io.s
- ab3d2_source/modules/music.s
- ab3d2_source/modules/system.s
- Fix startup bugs (VideoControlTags being called on invalid CM + CINIT not working as expected)
- Handle resource acquisition failures during loading (OOM/file not found). May still leak resources (file handles/memory in some cases though).
> Startup improvements

- ab3d2_source/objdrawhires.s
- Implements simple screen space guardband for polygon model rendering. Any polygon with a screen space vertex outside the guard band will be culled.
- Set to 8191, can be adjusted if this results in lost polygon glitches (I had to get almost inside a wall switch object to trigger it)
> Guardband fix for poly glitches

- ab3d2_source/bss/draw_bss.s
- ab3d2_source/bss/player_bss.s
- ab3d2_source/bss/zone_bss.s
- ab3d2_source/c/defs.h
- ab3d2_source/c/draw.c
- ab3d2_source/c/math25d.h
- ab3d2_source/c/multiplayer.h
- ab3d2_source/c/player.h
- ab3d2_source/c/zone.h
- ab3d2_source/c/zone_edge_pvs.c
- ab3d2_source/hires.s
- ab3d2_source/kmake.sh
- ab3d2_source/modules/dev_inst.s
- ab3d2_source/modules/draw/draw_zone_graph.s
Fixes issues with edge PVS caused by reliance purely on the Player 1 positional data.
> Bug: PVS issues in two-player mode

- ab3d2_source/c/game_preferences.c
- ab3d2_source/c/prefs_misc.h
- ab3d2_source/controlloop.s
- ab3d2_source/hires.s
- ab3d2_source/menu/menunb.s
added feature to 'custom options' menu to let the user turn off the 3d weapon models.
> Show weapon model option

- ab3d2_source/newanims.s
to allow the raise/lower speed to be set in levelED 3.15.5
> edit to water animation routine
